name: Lint
on: [push]
jobs:
  run:
    name: Run with Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '13' ]
    steps:
    - uses: actions/checkout@v2

    - name: Set Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node }}

    - name: npm install
      run: npm install

    - name: Lint
      run: npm run lint
